routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\StudentController;

///////////////// students routes
Route::resource('/students' , StudentController::class);
Route::get('/students/all' , [\App\Http\Controllers\StudentController::class , 'show'])->name('student.show');
Route::get('/student/home' , [\App\Http\Controllers\StudentController::class , 'home'])->name('studentHome');
//////////////////////////////////////////////////////////////////////////////////////////

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    protected $fillable = ['first_name' , 'last_name' , 'code' , 'point' ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{

    use SoftDeletes;
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];



    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StudentController extends Controller
{

    public function home()
    {
        return view('students.home');
    }

    public function index()
    {
        $students = Student::all();
        return view('students.show' , compact('students'));
    }
    public function show()
    {
        $students = DB::table('students')->orderBy('point' , 'desc')->take(4)->get();
        $low = DB::table('students')->orderBy('point' , 'asc')->take(3)->get();
        $avg = DB::table('students')->avg('point');
        return view('students.all' , compact('students' , 'low' , 'avg'));
    }

    public function all()
    {
        return view('students.all');
    }

    public function create(){
        return view('students.create');
    }

    public function store(Request $request){
        Student::create($request->all());
        return redirect()->route('students.index')->with('success' , 'عملیات ایجاد با موفقیت انجام شد');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('students.index')->with('success' , 'عملیات حذف با موفقیت انجام شد');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('students.edit' , compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $student = Student::find($id);
        $student ->update([
           'first_name' => $request->first_name ,
            'last_name' => $request->last_name ,
            'code' => $request->code ,
            'point' => $request->point ,
        ]);
        return redirect()->route('students.index')->with('success' , 'عملیات ,ویرایش با موفقیت انجام شد');
    }


}

app/Http/Controllers/sharkController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class sharkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
    @section('css-link')
    <link rel="stylesheet" href="{{asset('dist/bootstrap/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('dist/style.css')}}">
    @show
</head>
<body>

     <!-----------sTart template----------->
     <section class="w-100">

         @yield('content')
     </section>
     <!-----------eNd template----------->




<!----start js------->
     @section('js-link')
        <script src="{{asset('dist/bootstrap/bootstrap.min.js')}}"></script>
     @show

</body>
</html>

resources/views/students/all.blade.php
@extends('layouts.master')

@section('title' , 'show' )

@section('content')
    <section class="show-back">

        <h1 class="ordi text-secondary text-center py-3">اطلاعات و ویرایش اطلاعات ئانش آموزان</h1>

        <a class="main ordi mb-4" href="{{route('studentHome')}}">
            <section>
                خانه

                <div class="top-border"></div>
                <div class="bottom-border"></div>

            </section>
        </a>

        <section class="w-50 text-light text-center bg-success mx-auto p-4">
            <p class=" fw-bold bg-success fs-2 ordi">نفرات برتر</p>
        <table class="table table-hover table-dark mb-0" dir="rtl">
            <tr class="text-light text-center ordi fs-2">
                <td>نام</td>
                <td>نام خانوادگی</td>
                <td>نمره</td>
                <td>کد دانش آموزی </td>
            </tr>
{{--            {{dd($students)}}--}}
            @foreach($students as $student)
                <tr class="text-light text-center nazanin fs-3">
                    <td>{{ $student->first_name  }}</td>
                    <td>{{ $student->last_name  }}</td>
                    <td class="text-success fw-bolder">{{ $student->point  }} </td>
                    <td>{{ $student->code  }} </td>
                </tr>
            @endforeach
        </table>
        </section>

        <section class="w-50 bg-danger mx-auto p-4 mt-4">
            <p class=" fw-bold bg-danger text-center text-light fs-2 ordi">پایین ترین نمرات</p>
            <table class="table table-hover table-dark mb-0" dir="rtl">
                <tr class="text-light text-center ordi fs-2">
                    <td>نام</td>
                    <td>نام خانوادگی</td>
                    <td>نمره</td>
                    <td>کد دانش آموزی </td>
                </tr>
                {{--            {{dd($students)}}--}}
                @foreach($low as $lowest)
                    <tr class="text-light text-center nazanin fs-3">
                        <td>{{ $lowest->first_name  }}</td>
                        <td>{{ $lowest->last_name  }}</td>
                        <td class="text-danger fw-bolder">{{ $lowest->point  }} </td>
                        <td>{{ $lowest->code  }} </td>
                    </tr>
                @endforeach
            </table>
        </section>

        <section class="d-flex justify-content-between w-75 bg-light text-danger mx-auto my-5">
            <p class="fs-1 ordi ">{{$avg}}</p>
            <p class="fs-1 ordi text-dark">میانگین نمرات</p>
        </section>



    </section>
@stop

resources/views/students/create.blade.php
@extends('layouts.master')

@section('title' , 'Create' )

@section('content')
    <section class="w-100">
        <section class="w-50 mt-5 mx-auto">
            <form action="{{route('students.store')}}" method="post" dir="rtl">
                @csrf
                <label for="" class="ordi fs-3">نام</label>
                <input type="text" name="first_name" class="form-control nazanin fw-bolder fs-4">

                <label for="" class="ordi fs-3 mt-3"> نام خانوادگی </label>
                <input type="text" name="last_name" class="form-control nazanin fw-bolder fs-4">

                <label for="" class="ordi fs-3 mt-3"> نمره </label>
                <input type="number" name="point" class="form-control nazanin fw-bolder fs-4">

                <label for="" class="ordi fs-3 mt-3">کد </label>
                <input type="number" name="code" class="form-control nazanin fw-bolder fs-4">

                <input type="submit" class="btn btn-dark ordi px-4 py-1 mt-4 fs-4" value="ثبت">

            </form>

            <p class="ordi fw-bolder fs-2  mt-4 text-danger w-100 text-end">در صورت انجام شدن عملیات حتما پیامی مبنی بر موفقیت آمیز بودن آن دریافت خواهید کرد</p>

        </section>
    </section>
@stop

resources/views/students/edit.blade.php
@extends('layouts.master')

@section('title' , 'Create' )

@section('content')
    <section class="w-100">
        <section class="w-50 mt-5 mx-auto">
            <form action="{{route('students.update' , $student->id)}}" method="post" dir="rtl">
                @csrf
                @method('PUT')
                <label for="" class="ordi fs-3">نام</label>
                <input type="text" name="first_name" value="{{$student->first_name}}"  class="form-control nazanin fw-bolder fs-4">

                <label for="" class="ordi fs-3 mt-3"> نام خانوادگی </label>
                <input type="text" name="last_name" class="form-control nazanin fw-bolder fs-4"  value="{{$student->last_name}}">

                <label for="" class="ordi fs-3 mt-3"> نمره </label>
                <input type="number" name="point" class="form-control nazanin fw-bolder fs-4"  value="{{$student->point}}">

                <label for="" class="ordi fs-3 mt-3">کد </label>
                <input type="number" name="code" value="{{$student->code}}" class="form-control nazanin fw-bolder fs-4">

                <input type="submit" class="btn btn-dark ordi px-4 py-1 mt-4 fs-4" value="ثبت">

            </form>

            <p class="ordi fw-bolder fs-2  mt-4 text-danger w-100 text-end">در صورت انجام شدن عملیات حتما پیامی مبنی بر موفقیت آمیز بودن آن دریافت خواهید کرد</p>

        </section>
    </section>
@stop

resources/views/students/home.blade.php
@extends('layouts.master')

@section('title' , 'portable' )

@section('content')
    <section class="background">
        <div class="w-100 h-100">
            <section class="w-100 h-100">
                <h1 class="ordi text-light text-center display-2 pt-5">پورتابل دانش آموزی</h1>

                <section class="d-flex justify-content-center mt-5 pt-5">
                    <a class="mt-5 mx-5 d-flex flex-column portabl-item align-items-center fs-1" href="{{route('students.index')}}">
                        <img src="../images/signs/edit.svg" class="text-center" alt="edit.sign">
                        <p class="text-center text-light nazanin">ویرایش اطلاعات دانش آموزان</p>
                    </a>

                    <a class="mt-5 mx-5 d-flex  portabl-item flex-column align-items-center fs-1" href="{{route('student.show')}}">
                        <img src="../images/signs/result.svg" width="130px" class="text-center" alt="edit.sign">
                        <p class="text-center text-light nazanin">دیدن نتایج و نمرات</p>
                    </a>

                </section>

            </section>
        </div>
    </section>
@stop

resources/views/students/show.blade.php
@extends('layouts.master')

@section('title' , 'show' )

@section('content')
    <section class="show-back">

        <h1 class="ordi text-secondary text-center py-3">اطلاعات و ویرایش اطلاعات ئانش آموزان</h1>

        <a class="main ordi mb-4" href="{{route('studentHome')}}">
            <section>
          خانه

                <div class="top-border"></div>
                <div class="bottom-border"></div>

            </section>
        </a>

        <section class="d-flex justify-content-end p-4">
            <a href="{{route('students.create')}}" class="nazanin btn btn-light fw-bold fs-3">افزودن دانش آموز جدید</a>
        </section>

        @if($message = Session::get('success'))
            <section class="alert alert-success ordi">
                <p class="w-100 text-center fs-3">{{$message}}</p>
            </section>
        @endif

        <table class="table table-hover table-dark" dir="rtl">
            <tr class="text-light text-center ordi fs-2">
                <td>نام</td>
                <td>نام خانوادگی</td>
                <td>کد دانش آموزی </td>
                <td>نمره</td>
                <td>ویرایش</td>
                <td>حذف</td>
            </tr>

            @foreach($students as $student)
            <tr class="text-light text-center nazanin fs-3">
                <td>{{ $student['first_name']  }}</td>
                <td>{{ $student['last_name']  }}</td>
                <td>{{ $student['code']  }} </td>
                <td>{{ $student['point']  }}</td>
                <td><a href="{{route('students.edit' , $student->id)}}">
                        <img src="../images/signs/edit_icon.svg" width="40px" alt="dede">
                    </a></td>
                <td>
                    <form action="{{route('students.destroy' , $student->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <input type="submit" class="btn btn-danger ordi fw-bolder fs-4" value="حذف کردن">
                    </form>
                </td>
            </tr>
            @endforeach
        </table>
    </section>
@stop